version: "3"

services:
  web:
    build: .
    restart: 'always'
    depends_on:
      - mariadb
    ports:
      - '8081:80'
    links:
      - mariadb
  mariadb:
    image: "mariadb:10.7"
    restart: 'always'
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "MysQlR00tP@ssw0rd"
      MYSQL_DATABASE: "college_website_db"
      MYSQL_USER: "mysqluser"
      MYSQL_PASSWORD: "mysqlpass"
